package pers.spl.ziot.model;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.device_id
     *
     * @mbg.generated
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.value
     *
     * @mbg.generated
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.alert
     *
     * @mbg.generated
     */
    private Integer alert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.lat
     *
     * @mbg.generated
     */
    private Double lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.lng
     *
     * @mbg.generated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.device_id
     *
     * @return the value of message.device_id
     *
     * @mbg.generated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.device_id
     *
     * @param deviceId the value for message.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.time
     *
     * @return the value of message.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.time
     *
     * @param time the value for message.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.info
     *
     * @return the value of message.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.info
     *
     * @param info the value for message.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.value
     *
     * @return the value of message.value
     *
     * @mbg.generated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.value
     *
     * @param value the value for message.value
     *
     * @mbg.generated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.alert
     *
     * @return the value of message.alert
     *
     * @mbg.generated
     */
    public Integer getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.alert
     *
     * @param alert the value for message.alert
     *
     * @mbg.generated
     */
    public void setAlert(Integer alert) {
        this.alert = alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.lat
     *
     * @return the value of message.lat
     *
     * @mbg.generated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.lat
     *
     * @param lat the value for message.lat
     *
     * @mbg.generated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.lng
     *
     * @return the value of message.lng
     *
     * @mbg.generated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.lng
     *
     * @param lng the value for message.lng
     *
     * @mbg.generated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", time=").append(time);
        sb.append(", info=").append(info);
        sb.append(", value=").append(value);
        sb.append(", alert=").append(alert);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}